// React-Vite-Ts/src/App.tsx
import { Button } from 'antd';
import FaviconSVG from 'assets/favicon.svg';
import { uuid } from './utils';
import css from './index.module.less';

function App() {
  return (
    <div className={`flex items-center justify-center ${css.test}`}>
      <img src={FaviconSVG} className="logo" alt="Vite logo" height={100} width={100} key={uuid()} />
      <Button onClick={() => console.log('Hello')} key={uuid()}>Hello</Button>
      {uuid()}
    </div>
  );
}

export default App;

// template/Vue-Vite-Ts/src/App.vue
<template>
  <div class="text-center selection:bg-green-100">
    <img class="mx-auto mt-12 mb-8" alt="Vue logo" src="./assets/logo.png" :class="css.test" />
    <HelloWorld msg="Vite + Vue 3 + Typescript" />
    {{ css.test }}
  </div>
</template>

<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue';
import css from './index.module.less';
</script>
