// Vue-Vite-Ts/src/App.vue
<template>
  <div class="text-center selection:bg-green-100">
    <img class="mx-auto mt-12 mb-8" alt="Vue logo" src="./assets/logo.png" :class="css.test" />
    <HelloWorld msg="Vite + Vue 3 + Typescript" />
    {{ css.test }}
  </div>
</template>

<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
import css from "./index.module.less";
console.log(css);
</script>

// template/React-Vite-Ts/src/App.tsx
import { Button, Image } from 'antd';
import FaviconSVG from 'assets/favicon.svg';
import { uuid } from './utils';
import { uuid1 } from 'zhuba-tools';
import css from './index.module.less';
import { useNumStore } from 'store';

function App() {
  const { num, increasePopulation } = useNumStore();
  return (
    <>
      <div className={`flex items-center justify-center ${css.test}`}>
        <Image
          src={FaviconSVG}
          className="logo"
          alt="Vite logo"
          height={100}
          width={100}
          key={uuid()}
        />
        <Button
          onClick={() => {
            console.log('Hello');
            increasePopulation();
          }}
          key={uuid1()}
        >
          {num}
        </Button>
      </div>
      <div className={`flex items-center justify-center`}>
        <Image src={'https://api.52starxi.cn/api/img-4k/img.php'} style={{ width: '80vw' }}></Image>
      </div>
    </>
  );
}

export default App;
